image: node:10.16

before_script:
  - npm i -g yarn
  - yarn

cache:
  paths:
    - ./node_modules

test:node:10.16:
  image: node:10.16
  script:
    - yarn lint
    - yarn test

sast:
  script:
    - docker run --interactive --tty --rm --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock registry.gitlab.com/gitlab-org/security-products/sast:${VERSION:-latest} /app/bin/run /code
