name: Run iOS Simulator Tests

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 30

    env:
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app
    steps:
      - uses: actions/checkout@master

      - name: Select Xcode
        run: sudo xcode-select -s '/Applications/Xcode_11.3.1.app/Contents/Developer'

      - uses: actions/setup-node@master

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox-setup

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: yarn pod-install

      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: yarn detox build e2e --configuration ios.sim.release
      - run: yarn detox test e2e --configuration ios.sim.release --cleanup --debug-synchronization 200 --artifacts-location /tmp/detox_artifacts --record-videos failing

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: detox-artifacts
          path: /tmp/detox_artifacts
