name: Run unit tests (by jest)

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image: node:10.16

    steps:
      - uses: actions/checkout@v1
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn test

