name: Run unit tests (by jest)

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image: node:10.16

    steps:
      - uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test

